language: node_js
node_js:
  - '16'
matrix:
  include:
  - os: linux
    dist: xenial
  - os: windows
cache:
  npm: true

addons:
  apt_packages:
    - rpm

script:
  - npm run build
  
deploy:
  - provider: releases
    api_key:
      secure: "Eh2WAmwoIZIpL+BEvBLEsl8f2EpWODX0smLFw8igHYnfo7CFjXzoVSOiXzJZpozwdUZtjp28CIgwNSmNwHFEmvNbY/HxPFCTxss6s27oHKe5K5d6vmVIn6L2Cf6HskcqWgJrYcbzYk1klsWnnTyeYWpw2K8bnctq1pC913y7NFHc89McP6X2v+jDdy6vCJQ8lPJsgLmVU1TiiNFH84ynWxDYLbtsV4RoF/JSR1aetyBkoQYZSC3TGLFZVfQ4Ka4V/Sc1BQsjlopBhE99TPGgWHQbtx06YMpAGjXGwn+sKmWZzyZwYN9itUBVjj2ZH146NwNLdX19X15R0qFaoCWciqgPdE1gxwGwpKv++I0Ec1+nG/hVTVKcKLCybsNJL8q9NnqFsEIPjUmLusKVsZOAr/t5WgduCZGdvidC7if4m+yFFUaIvG1j6kKT6nKPPL3rBiWZZ3CYEumUxU+MjI7UjfvWkFubdYxTuk7lCNjmJPVUzCA+hJkrIbVWbn/3YTTdhraOL5lMDu5uP0caQJJNW64TIpgcPFRTt0SqAAhQSt029D2ycjnOOOPscmFBzvJ9qSXsjRGZNQC2eCSfLjWd7bYW8Bph8HyZkp3SPWJu6jCJp2rkx/lslgQmkVgjBxErtZmdZxkKBIRH55I0pHBsaBwsWGi/cMxK7xJ8oL3rHmM="
    skip_cleanup: true

  - provider: snap
    snap: notewriter*.snap
    channel: release
    skip_cleanup: true