language: node_js
node_js:
  - '14'
matrix:
  include:
  - os: linux
    dist: xenial
  - os: windows
cache:
  npm: true
script:
  - npm run build
deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
