# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ desktop-app ]
  pull_request:
    branches: [ desktop-app ]

jobs:
  release:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest, windows-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Electron Builder Action
      uses: samuelmeuli/action-electron-builder@v1.6.0
      with:
        # GitHub authentication token
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release: ${{ startsWith(github.ref, 'refs/tags/v') }}
